Controllers/FoodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApplication.Models;
using WebApplication.DAL;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApplication.Controllers
{
    public class FoodController : Controller
    {
        //DAL
        //=======================================================================================
        CustomerDAL CustomerContext = new CustomerDAL();
        CartDAL CartContext = new CartDAL();
        FoodDAL FoodContext = new FoodDAL();
        //=======================================================================================

        //=======================================================================================
        public IActionResult Index()
        {
            return View();
        }
        //=======================================================================================

        //=======================================================================================
        public ActionResult FoodStores()
        {
            List<Store> StoreList = FoodContext.GetAllStores();
            return View(StoreList);
        }
        //=======================================================================================

        //=======================================================================================
        public async Task<IActionResult> FoodStoreItems(int? id, int? QTY, int? ItemID)
        {
            List<Item> FoodList = new List<Item>();
            if(ItemID != null)
            {
                //Add items into cart
                Customer customer = CustomerContext.GetDetails(Convert.ToString(HttpContext.Session.GetString("LoginID")));
                CartItems cartItem = CartContext.CheckIfItemInCart(customer.ID, Convert.ToInt32(ItemID));
                if (cartItem != null)
                {
                    cartItem.qty += Convert.ToInt32(QTY);
                    CartContext.UpdateCartItem(cartItem);
                }
                else
                {
                    CartItems cartData = new CartItems
                    {
                        CustomerID = customer.ID,
                        ItemID = Convert.ToInt32(ItemID),
                        qty = Convert.ToInt32(QTY)

                    };
                    CartContext.AddItemIntoCart(cartData);
                }
                
            }
            string StoreName = FoodContext.GetStore(Convert.ToInt32(id)).StoreName;
            FoodList = FoodContext.GetFoodItems(StoreName);
            TempData["StoreName"] = StoreName;
            return View(FoodList);
        }
        //=======================================================================================
    }
}

Views/Food/FoodStoreItems.cshtml
@model IEnumerable<WebApplication.Models.Item>
@{
    ViewData["Title"] = "FoodStoreItems";
}

<html>
<head>
    <!-- Use Unicode character encoding - multi-language compatibity -->
    <meta charset="utf-8">          <!-- Set the initial view zooming scale for mobile device  -->
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="true">
    <title>B-United SG</title>          <!-- Reference to customized styling for this website -->
    <link href="https://fonts.googleapis.com/css2?family=Quicksand&display=swap" rel="stylesheet">
    <script src="~/js/Navbar.js" defer></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/FoodStoreItems.css" />
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
</head>
<body>
    <div class="row styleDiv" style="padding: 20px 0 20px 0;">
        <div class="col-sm-12 styleDiv">
            <h1>@TempData["StoreName"]</h1>
        </div>
    </div>
    <div class="jumbotron" style="background-color: pink; padding: 0px;">
        <div class="row col-sm-12" style="font-size: 25px;">
            <div class="container-fluid">
                <table class="table" style="text-align: center;">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            Price ($)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Status)
                        </th>
                        <th>
                            Dietary Restrictions
                        </th>
                        <th></th>
                    </tr>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.Status != "Deleted")
                            {
                                <tr>
                                    <td>
                                        @item.Name
                                    </td>
                                    <td>
                                        @item.Price
                                    </td>
                                    @if (item.Status == "Available")
                                    {
                                     <td style="color: forestgreen">
                                        @item.Status
                                    </td>
                                    }
                                    else
                                    {
                                    <td style="color: red">
                                        @item.Status
                                    </td>
                                    }
                                    <td>
                                        @item.Dietary
                                    </td>
                                    <td>
                                        <form asp-action="FoodStoreItems" method="post">
                                            <div class="input-group">
                                                <input type="text" hidden name="ItemID" value="@item.ItemID" class="form-control" aria-describedby="basic-addon1" />
                                            </div>
                                            <div class="input-group">
                                                <input type="number" name="QTY" id="qty_@item.ItemID" placeholder="Enter quantity" class="form-control" aria-describedby="basic-addon1" min="1" required />
                                            </div>
                                            <div class="input-group" style="margin-top:5px">
                                                <input type="submit" value="Add to food cart" class="form-control btn btn-danger" aria-describedby="basic-addon1" onclick="addcart('#qty_@item.ItemID')" />
                                            </div>
                                        </form>
                                    </td>
                                </tr>
                            }

                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <a class="btn btn-danger" asp-controller="Food" asp-action="FoodStores">Back To Stores</a>
        </div>
        <div class="col-sm-6" style="text-align: right;">
            <a class="btn btn-danger" asp-controller="Cart" asp-action="ViewCart">View Cart</a>
        </div>
    </div>

</body>
</html>
<script type="text/javascript">
    function addcart(id) {
        if ($(id).val() == 0) {
            alert("Please enter the qty");
        }
        else {
            alert("Item added to cart successfully!");
        }
        
    }
</script>

Views/Food/FoodStores.cshtml
@model IEnumerable<WebApplication.Models.Store>
@{
    ViewData["Title"] = "FoodStores";
}

<html>
<head>
    <!-- Use Unicode character encoding - multi-language compatibity -->
    <meta charset="utf-8">          <!-- Set the initial view zooming scale for mobile device  -->
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="true">
    <title>B-United SG</title>          <!-- Reference to customized styling for this website -->
    <link href="https://fonts.googleapis.com/css2?family=Quicksand&display=swap" rel="stylesheet">
    <script src="~/js/Navbar.js" defer></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/FoodStores.css" />
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
</head>
<body>
    <div class="row styleDiv" style="padding: 20px 0 40px 0;">
        <div class="col-sm-12 styleDiv">
            <h2 style="font-weight: bold;">Select a food store</h2>
            <h2>Order your food from these available food stores!</h2>
        </div>
    </div>
    <div class="row" style="padding-bottom: 20px;">
        <div class="col-sm-12">
            <input style="width: 100%; padding:10px;" type="text" placeholder="Looking for something? e.g. starbucks" id="myStore" onkeyup="myFunction()" />
        </div>
    </div>
    <ul style="padding: 0px;" id="myUL">
        @{int i = 1;}
        @foreach (var item in Model)
        {
            <li><a asp-route-id="@item.ID" type="button" asp-action="FoodStoreItems" asp-controller="Food" name="StoreID" style="font-weight: bold;" id="myLI">@item.StoreName <p style="font-size: 15px !important">Location: @item.Area</p></a></li>
            i++;
        }
    </ul>
    <a class="btn btn-danger" href="~/Customer/Index">Back to home</a>
        <script>
            function myFunction() {
                // Declare variables
                var input, filter, ul, li, a, i, txtValue;
                input = document.getElementById('myStore');
                filter = input.value.toUpperCase();
                ul = document.getElementById("myUL");
                li = ul.getElementsByTagName('li');

                // Loop through all list items, and hide those who don't match the search query
                for (i = 0; i < li.length; i++) {
                    a = li[i].getElementsByTagName("a")[0];
                    txtValue = a.textContent || a.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        li[i].style.display = "";
                        ul.style.padding = "0px";
                        li[i].style.margin = "10px";
                    } else {
                        li[i].style.display = "none";
                        ul.style.backgroundColor = "none";
                        ul.style.padding = "0";
                    }
                }
            }
        </script>
    </body>
</html>