Controllers/GroceryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApplication.Models;
using WebApplication.DAL;

namespace WebApplication.Controllers
{
    public class GroceryController : Controller
    {
        //DAL
        GroceryDAL GroceryContext = new GroceryDAL();
        CartDAL CartContext = new CartDAL();
        CustomerDAL CustomerContext = new CustomerDAL();

        public async Task<IActionResult> ViewGrocery(int? ID)
        {
            List<Item> GroceryList = new List<Item>();
            if (ID != null)
            {
                //Add items into cart
                Customer customer = CustomerContext.GetDetails(Convert.ToString(HttpContext.Session.GetString("LoginID")));
                CartItems cartItem = CartContext.CheckIfItemInCart(customer.ID, Convert.ToInt32(ID));
                if (cartItem != null)
                {
                    cartItem.qty += 1;
                    CartContext.UpdateCartItem(cartItem);
                }
                else
                {
                    CartItems cartData = new CartItems
                    {
                        CustomerID = customer.ID,
                        ItemID = Convert.ToInt32(ID),
                        qty = Convert.ToInt32(1)

                    };
                    CartContext.AddItemIntoCart(cartData);
                }

            }
            GroceryList = GroceryContext.GetItems();
            return View(GroceryList);
        }
    }
}

Views/Grocery/Checkout.cshtml
@*@model IEnumerable<WebApplication.Models.CartViewModel>*@

@{
    ViewData["Title"] = "Checkout";
}

<html>
<head>
    <!-- Use Unicode character encoding - multi-language compatibity -->
    <meta charset="utf-8">          <!-- Set the initial view zooming scale for mobile device  -->
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="true">
    <title>B-United SG</title>          <!-- Reference to customized styling for this website -->
    <link href="https://fonts.googleapis.com/css2?family=Quicksand&display=swap" rel="stylesheet">
    <script src="~/js/Navbar.js" defer></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/GroceryCheckout.css" />
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
</head>

<body>
    <div class="row styleDiv">
        <div class="col-sm-12 styleDiv">
            <h1 style="font-weight: bold;">Order Summary</h1>
        </div>
    </div>
    <div style=" background-color: pink; padding-left:20px; border-radius:10px;">
        <div style="font-size: 25px;">
            <table class="table table-borderless">
                <tr>
                    <th><u>Item</u></th>
                    <th><u>Brand</u></th>
                    <th><u>Price</u></th>
                    <th><u>Quantity</u></th>

                </tr>
                @*@foreach (var item in Model)
                {
                    <tbody>
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.Brand</td>
                            <td>@item.Price</td>
                            <td>@item.Quantity</td>
                        </tr>
                    </tbody>
                }*@
            </table>
            <hr class="new4" />
        </div>
        <div class="row" style="font-size: 25px;">
            <div class="col-sm-9" style="text-align: left; padding-left: 25px;">
                <p>Total: </p>
            </div>
            <div class="col-sm-3" style="text-align: left; padding-left: 10px;">
                <p>$@ViewData["TotalCost"]</p>
            </div>
        </div>
        @*<div class="row" style="font-size: 25px;">
            <div class="col-sm-9" style="text-align: left; padding-left: 25px;">
                <p>Delivery Fees: </p>
            </div>
            <div class="col-sm-3" style="text-align: left; padding-left: 10px;">
                <p>$1.65</p>
            </div>
        </div>*@
    </div>
    <div class="row styleDiv divMargin">
        <div class="col-sm-12 styleDiv">
            <h1 style="font-weight: bold;">Deliver to</h1>
        </div>
    </div>
    <div>
        <div style=" background-color: pink; padding-left:20px; border-radius:10px; margin: 0px;">
            <div class="row" style="font-size: 25px; padding: 20px 0 0 0;">
                <div class="col-sm-9">
                    <p>@ViewData["Address"]</p>
                </div>
                <div class="col-sm-3">
                    <p><u><a href="~/Customer/Edit" style="color: black;">Edit</a></u></p>
                </div>
            </div>
        </div>
    </div>

    <div class="row styleDiv">
        <div class="col-sm-12 styleDiv">
            <h1 style="font-weight: bold;">Payment Details</h1>
        </div>
    </div>
    <div style=" background-color: pink; padding-left:20px; border-radius:10px;" class="styleDiv">
        <div class="row" style="font-size: 25px; margin: 0px;">
            <div class="col-sm-12" style="text-align: center;">
                <p>Cash</p>
            </div>
        </div>
    </div>
    <hr class="new4" />
    <div class="row" style="font-size: 25px;">
        <div class="col-sm-9" style="text-align: left; padding-left: 25px;">
            <p>Total: </p>
        </div>
        <div class="col-sm-3" style="text-align: left; padding-left: 10px;">
            <p>@ViewData["TotalCost"]</p>
        </div>
    </div>

    <div class="row" style="padding-top: 20px;">
        <div class="col-sm-12">
            <a href="~/Grocery/CreateOrder" type="button" style="width:100%; text-align:center; justify-content:center;  padding: 10px;" class="btn btn-success">Place Order</a>
        </div>
    </div>
</body>
</html>

Views/Grocery/ViewCart.cshtml
@*@model IEnumerable<WebApplication.Models.CartViewModel>*@

@{
    ViewData["Title"] = "ViewCart";
}

<html>
<head>
    <!-- Use Unicode character encoding - multi-language compatibity -->
    <meta charset="utf-8">          <!-- Set the initial view zooming scale for mobile device  -->
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="true">
    <title>B-United SG</title>          <!-- Reference to customized styling for this website -->
    <link href="https://fonts.googleapis.com/css2?family=Quicksand&display=swap" rel="stylesheet">
    <script src="~/js/Navbar.js" defer></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/ViewCart.css" />
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
</head>
<body>
    <div class="row styleDiv" style="padding: 20px 0 40px 0;">
        <div class="col-sm-12 styleDiv">
            <h1 style="font-weight: bold;">View Grocery Cart</h1>
        </div>
    </div>
    <h2 style="color:red;">@TempData["CartEmpty"]</h2>
    <div class="jumbotron" style="background-color: pink; padding: 0px;">
        <div class="row col-sm-12" style="font-size: 25px;">
            <div class="container-fluid">
                <table class="table table-borderless" style="text-align: center;">
                    <tr>
                        <th>Name</th>
                        <th>Brand</th>
                        <th>Description</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th></th>
                    </tr>

                    @*@foreach (var item in Model)
                        {
                            <tbody>
                                <tr>
                                    <td>@item.Name</td>
                                    <td>@item.Brand</td>
                                    <td>@item.Description</td>
                                    <td>@item.Quantity</td>
                                    <td>@item.Price</td>
                                    <td><a class="btn btn-outline-danger" asp-action="DeleteCartItem" asp-controller="Grocery" asp-route-id="@item.ID">Delete</a></td>
                                </tr>
                            </tbody>
                        }*@
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <a class="btn btn-danger" asp-controller="Customer" asp-action="OrderGrocery">Back</a>
        </div>
        <div class="col-sm-6" style="text-align: right;">
            <a class="btn btn-danger" asp-controller="Grocery" asp-action="Checkout">Checkout</a>
        </div>
    </div>
</body>
</html>

Views/Grocery/ViewGrocery.cshtml
@model IEnumerable<WebApplication.Models.Item>
@{
    ViewData["Title"] = "OrderGrocery";
}
<html>
<head>
    <!-- Use Unicode character encoding - multi-language compatibity -->
    <meta charset="utf-8">          <!-- Set the initial view zooming scale for mobile device  -->
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="true">
    <title>B-United SG</title>          <!-- Reference to customized styling for this website -->
    <link href="https://fonts.googleapis.com/css2?family=Quicksand&display=swap" rel="stylesheet">
    <script src="~/js/Navbar.js" defer></script>
    <link rel="stylesheet" href="~/css/orderGrocery.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div class="row styleDiv" style="padding: 20px 0 40px 0;">
        <div class="col-sm-12 styleDiv">
            <h2 style="font-weight: bold;">Grocery Shopping!</h2>
            <h2>Select grocery to add to cart</h2>
        </div>
    </div>
    <div class="jumbotron" style="background-color: pink; padding: 0px;">
        <div class="row col-sm-12" style="font-size: 25px;">
            <div class="container-fluid">
                <table class="table" style="text-align: center;">
                    <tr>
                        <th>Product Name</th>
                        <th>Price ($)</th>
                        <th>Status</th>
                        <th></th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        if (item.Status != "Deleted")
                        {
                            <tbody>
                                <tr>
                                    <td>@item.Name</td>
                                    <td>@item.Price</td>
                                    @if (item.Status == "Available")
                                    {
                                        <td style="color: forestgreen">
                                            @item.Status
                                        </td>
                                        <td><a type="button" class="addButton" asp-action="ViewGrocery" asp-controller="Grocery" asp-route-id="@item.ItemID" onclick="addcart()">Add to cart <i class="fa fa-shopping-basket"></i></a></td>
                                    }
                                    else
                                    {
                                        <td style="color: red">
                                            @item.Status
                                        </td>
                                    }
                                </tr>
                            </tbody>
                        }

                    }
                </table>
            </div>
        </div>
    </div>
    <div class="row" style="padding-top: 20px;">
        <div class="col-sm-6">
            <a class="btn btn-danger" asp-controller="Customer" asp-action="Index">Back To Home</a>
        </div>
        <div class="col-sm-6" style="text-align: right;">
            <a class="btn btn-danger" asp-controller="Cart" asp-action="ViewCart">View Cart</a>
        </div>
    </div>
    <script type="text/javascript">
        function addcart() {
            alert("Item added to cart successfully!");
        }
    </script>
</body>
</html>